### ISSUE TITLE
Battle Tracker

### ISSUE THREAD

**Issue by Wegi** [Wegi/rpscene#34]
* [ ] Add NPCs / Stubs and forward the combat one by one. 
* [ ] Allow adding of players initiative.
* [ ] Allow rolling / fix initiative / entering of initiative for NPCs
* [ ] Keep track of resources of NPCs
* [ ] Roundtimer 
* [ ] Keep Track of Effects
* [ ] Overview and Focus on current player Views.
